// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amjgcqfrcwqkrkzktsuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtamdjcWZyY3dxa3Jremt0c3VqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NjExOTQsImV4cCI6MjA3MDMzNzE5NH0.DcnDnWDRSPPQoUrh1UhTVhIO6na9ZeC_tjEgl_Ce-wM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});